[project]
name = "app"
version = "0.1.0"
description = "Zeron Email Service"
authors = [
    {name = "rohithakur0208", email = "rohit@zeron.one"},
]
dependencies = []
requires-python = ">=3.12"
readme = "README.md"
license = {text = "MIT"}

[build-system]
requires = ["pdm-backend"]
build-backend = "pdm.backend"


[tool.pdm]
distribution = true
