[project]
name = "sandesh-sdk"
version = "0.3.0"
description = "Official Python SDK for the Sandesh notification API."
authors = [
    {name = "Rohit Thakur", email = "rohit@zeron.one"},
]
dependencies = [
    "httpx>=0.25.0",
]
requires-python = ">=3.9"
readme = "README.md"
license = {text = "CC BY-NC 4.0"}
keywords = ["sandesh", "notifications", "sdk", "api-client"]
classifiers = [
    "Development Status :: 4 - Beta",
    "Intended Audience :: Developers",
    "License :: Other/Proprietary License",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3 :: Only",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Topic :: Software Development :: Libraries :: Python Modules",
]

[build-system]
requires = ["pdm-backend"]
build-backend = "pdm.backend"


[tool.pdm]
distribution = true

[tool.pdm.build]
includes = ["sandesh/"]
