# License: MIT
# Typing stubs for sandesh.sdk.client
from __future__ import annotations

from types import TracebackType
from typing import Any, Dict, List, Mapping, Optional, Type

import httpx

JsonDict = Dict[str, Any]

class Sandesh:
    def __init__(
        self, base_url: str, bearer_token: str, timeout: float = 60.0
    ) -> None: ...
    def _client(self) -> httpx.Client: ...
    def close(self) -> None: ...
    def __enter__(self) -> Sandesh: ...
    def __exit__(
        self,
        exc_type: Optional[Type[BaseException]],
        exc: Optional[BaseException],
        tb: Optional[TracebackType],
    ) -> None: ...
    def _request(
        self,
        method: str,
        path: str,
        *,
        params: Optional[Mapping[str, Any]] = None,
        json: Optional[JsonDict] = None,
    ) -> Any: ...
    def events_trigger(self, body: JsonDict) -> JsonDict: ...
    def events_trigger_legacy(self, body: JsonDict) -> JsonDict: ...
    def create_subscriber(self, body: JsonDict) -> JsonDict: ...
    def update_subscriber(
        self, subscriber_id: str, body: JsonDict
    ) -> JsonDict: ...
    def get_subscriber(self, subscriber_id: str) -> JsonDict: ...
    def list_subscribers(self) -> List[JsonDict]: ...
    def deactivate_subscriber(self, subscriber_id: str) -> JsonDict: ...
    def get_notifications(
        self,
        *,
        status: Optional[str] = None,
        template_id: Optional[str] = None,
        email: Optional[str] = None,
        limit: int = 100,
        offset: int = 0,
    ) -> List[JsonDict]: ...
    def create_notification(self, body: JsonDict) -> JsonDict: ...
    def create_notification_v1(self, body: JsonDict) -> JsonDict: ...
    def get_notification(self, notification_id: int) -> JsonDict: ...
    def mark_notification_seen(self, notification_id: int) -> JsonDict: ...
    def mark_notification_unseen(self, notification_id: int) -> JsonDict: ...
    def retry_notification(self, notification_id: int) -> JsonDict: ...
    def resend_notification(self, notification_id: int) -> JsonDict: ...
    def integrations_status(self) -> JsonDict: ...
    def integrations_me(self) -> JsonDict: ...
    def integrations_me_update(self, body: JsonDict) -> JsonDict: ...
    def list_templates(
        self,
        *,
        limit: int = 100,
        offset: int = 0,
        active_only: bool = False,
    ) -> List[JsonDict]: ...
    def create_template(self, body: JsonDict) -> JsonDict: ...
    def get_template(self, template_id: str) -> JsonDict: ...
    def update_template(self, template_id: str, body: JsonDict) -> JsonDict: ...
    def delete_template(self, template_id: str) -> JsonDict: ...
    def preview_template(self, body: JsonDict) -> JsonDict: ...
    def validate_template(self, body: JsonDict) -> JsonDict: ...
    def list_credentials(
        self, *, channel: Optional[str] = None
    ) -> List[JsonDict]: ...
    def create_credential(self, body: JsonDict) -> JsonDict: ...
    def get_credential(self, cred_id: int) -> JsonDict: ...
    def update_credential(self, cred_id: int, body: JsonDict) -> JsonDict: ...
    def set_default_credential(self, cred_id: int) -> JsonDict: ...
    def delete_credential(self, cred_id: int) -> JsonDict: ...
    def get_email_settings(self) -> JsonDict: ...
    def update_email_settings(self, body: JsonDict) -> JsonDict: ...
    def test_email_settings(self, body: JsonDict) -> JsonDict: ...
    def get_ses_settings(self) -> JsonDict: ...
    def get_ses_quota(self) -> JsonDict: ...
    def get_verified_emails(self) -> JsonDict: ...
    def verify_email(self, email: str) -> JsonDict: ...
    def get_stats(self) -> JsonDict: ...
    def health(self) -> JsonDict: ...
